{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"pokemon\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "de-DE",
    "cultures": [
      {
        "name": "de-DE",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "de-DE",
    "tables": [
      {
        "name": "DateTableTemplate_8ec97788-7ae9-43b0-8eb5-35ab7fe129c9",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "af970919-f094-4f3b-a281-bf4c41b760d0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Jahr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "176156d2-ba67-43f1-9e02-74ec9ee070b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Monat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b9b5e403-875c-4458-942a-03b1b1b8dc69",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b5daf90a-7bd6-4916-bc25-443057418800",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quartal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qrtl \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "36b47405-064f-4532-bf65-f6252c6c8576",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a6a40764-2200-4441-b121-6abe36df96a2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Tag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f7f3f7a-0077-4b0b-9d28-e20d10dcccd6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Datumshierarchie",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Jahr",
                "column": "Jahr",
                "lineageTag": "9d59c88d-64d6-4f57-b803-9b643ae892eb",
                "ordinal": 0
              },
              {
                "name": "Quartal",
                "column": "Quartal",
                "lineageTag": "931f0213-73ce-44ea-808b-e9a99b604238",
                "ordinal": 1
              },
              {
                "name": "Monat",
                "column": "Monat",
                "lineageTag": "94b3f8f2-bf9b-4ce6-8c1a-10870011122c",
                "ordinal": 2
              },
              {
                "name": "Tag",
                "column": "Tag",
                "lineageTag": "a954a209-7eb3-40d6-82ae-d35cca4da071",
                "ordinal": 3
              }
            ],
            "lineageTag": "5b76ec0a-e7ef-49bb-bda8-d1ab7498d051"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "daaac356-beab-47e1-a87e-507c9c9d6ab8",
        "partitions": [
          {
            "name": "DateTableTemplate_8ec97788-7ae9-43b0-8eb5-35ab7fe129c9-609199bc-ae8c-4b39-aa63-dedf1176d6d6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "pokemon",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "#",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46feab73-6519-4600-853c-f970d4686cff",
            "sourceColumn": "#",
            "summarizeBy": "sum"
          },
          {
            "name": "Attack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb5b54f6-5c48-4723-9f11-2d902a476618",
            "sourceColumn": "Attack",
            "summarizeBy": "sum"
          },
          {
            "name": "Defense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87e9ec36-1f36-4462-8cde-616942896a23",
            "sourceColumn": "Defense",
            "summarizeBy": "sum"
          },
          {
            "name": "Generation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f1b57cd-62de-446e-bca6-13377e494fcb",
            "sourceColumn": "Generation",
            "summarizeBy": "sum"
          },
          {
            "name": "HP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea68ee1c-eed8-4702-88a6-381956e219d1",
            "sourceColumn": "HP",
            "summarizeBy": "sum"
          },
          {
            "name": "Legendary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cce2e15c-1d0d-469e-a226-3ca565dbf6ac",
            "sourceColumn": "Legendary",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6c282cf-1a12-4b00-a9a1-7c1a2a503499",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sp. Atk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a159cbe4-4256-47cc-9701-6d145548d6a9",
            "sourceColumn": "Sp. Atk",
            "summarizeBy": "sum"
          },
          {
            "name": "Sp. Def",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6626d1e-90ce-4159-ab84-e6efebce76dd",
            "sourceColumn": "Sp. Def",
            "summarizeBy": "sum"
          },
          {
            "name": "Speed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1e6014eb-3550-41dc-bf01-893f003b05b5",
            "sourceColumn": "Speed",
            "summarizeBy": "sum"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "adf6c2cc-c9ef-439f-b5d5-1e898e878c52",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Type 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86d7ca98-cdf5-4bb7-b6f6-48fb3dab74e9",
            "sourceColumn": "Type 1",
            "summarizeBy": "none"
          },
          {
            "name": "Type 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19652578-b859-4358-96fb-e8566e7fa083",
            "sourceColumn": "Type 2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "133e0132-c025-41cf-b2ce-ba61bc5ac00a",
        "partitions": [
          {
            "name": "pokemon-0e17ffa5-6299-4519-8275-278c4d9b50a4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://gist.githubusercontent.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6/raw/92200bc0a673d5ce2110aaad4544ed6c4010f687/pokemon.csv\"),[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"#\", Int64.Type}, {\"Name\", type text}, {\"Type 1\", type text}, {\"Type 2\", type text}, {\"Total\", Int64.Type}, {\"HP\", Int64.Type}, {\"Attack\", Int64.Type}, {\"Defense\", Int64.Type}, {\"Sp. Atk\", Int64.Type}, {\"Sp. Def\", Int64.Type}, {\"Speed\", Int64.Type}, {\"Generation\", Int64.Type}, {\"Legendary\", type logical}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}